### ISSUE TITLE
Self-referencing Navigations Not Generated

### ISSUE THREAD

**Issue by 2xRon** [R4ND3LL/EdmxRuler#2] opened 2022-12-11 19:26 UTC
First, let me say, workflow-wise this is shaping up to be exactly what we're looking for and will probably replace EFPT for us.

We have a number of tables that use self-referencing columns as a sort of history table. It seems that scaffolding with EFR skips the navigation and reverse navigation properties for those FKs (the correct column name is still generated).

**Comment by R4ND3LL** [comment] 2022-12-11 20:43
Thanks, @2xRon. It does seem to be shaping up, filling a few gaps in the reverse engineer process. 

Seems odd since the self referencing nav is nothing special. 

Can you confirm that scaffolding without EFR Design referenced does generate the navs normally? 

Also, does the json file have the correct FK names for those relations?  The names are gathered from the EDMX but sometimes that goes out of sync from the DB if changed afterwards in the DB. 

For one of the tables in question, set "IncludeUnknownColumns" to true and see if that resolves it.

**Comment by 2xRon** [comment] 2022-12-11 21:19
Ah that first point was the main problem. Looks like these relationships/navigations only exist in the edmx and don't have corresponding FK constraints in the DB for those columns. I get it if that's outside the scope of this project.

**Comment by R4ND3LL** [comment] 2022-12-11 21:47
Currently, elements that are customized have to at least exist in the DB.  However it's conceivable to build extra navigations on the fly. 

This is something I'd have to plan for a bit later if there's call for it.

**Comment by R4ND3LL** [comment] 2022-12-13 14:11
@2xRon, as a simple workaround, turn on config file splitting in the rules.json:

> "SplitEntityTypeConfigurations": true

This will give you separate entity config files within partial classes so that you can easily extend the configuration using:

> partial void OnConfigurePartial(..) {}

Create your additions in a separate file and they wont be overwritten each time you scaffold.

**Comment by 2xRon** [comment] 2022-12-13 14:17
Yup, this is what I'm doing now - nifty feature partial classes/functions is!

As an aside, is it intended that the dbset names don't get pluralized if the entity is renamed? I can open that as a new ticket.

**Comment by R4ND3LL** [comment] 2022-12-13 14:26
> As an aside, is it intended that the dbset names don't get pluralized if the entity is renamed? I can open that as a new ticket.

Open away  - that shouldn't be.

**Comment by R4ND3LL** [comment] 2022-12-13 23:17
DbSet pluralization fixed in [v1.1.6](https://www.nuget.org/packages/EntityFrameworkRuler.Design/#readme-body-tab)
Also added json property DbSetName to navigations for customization.  [VS Extension v1.0.69](https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler&ssr=false#overview)

**Comment by R4ND3LL** [comment] 2023-01-28 12:20
FYI, design time navigations are now supported, such as adding navigations to views.   Table splitting and inheritance is also supported since the creation of this issue.  You would need to regenerate a json file from the EDMX, however, as there is additional FK mapping information that EFR has to capture.  Then scaffold as usual.

**Comment by 2xRon** [comment] 2023-01-28 20:41
That's awesome, you're the best!

I gave it a try, but it seems like ~80% of the navigations aren't generated with the message "...does not form a valid constraint." Many (but not all) of them are self-referencing navigations (parent row etc). I'd like to help, but I'm not quite sure how to attach the debugger at design-time.

**Comment by R4ND3LL** [comment] 2023-01-28 20:57
that error would be raised when the constraint's dependent columns or principal columns are not found on the table.  The column count on each side of the constraint should also match (normally 1).

Can you check one of the FKs in question and verify that the definition of that FK in the JSON does have columns defined and that they exist on the table?  In the Rule Editor, you'll see them on the FOREIGNKEYS tab (when root node selected)

**Comment by 2xRon** [comment] 2023-01-28 22:31
Checked out a few broken ones, they look Ok to me. One thing different is the PK column on the principle end tends to have a Name, PropertyName, and a NewName defined with only a casing difference between Name and PropertyName.

**Comment by R4ND3LL** [comment] 2023-01-28 22:54
If I can reproduce the issue then I can resolve it.  Would it be possible to provide an EDMX+DB creation script (or at least a reduced down version that exhibits the problem)?  If you want, I can pass my email over so that you can send it directly.

**Comment by 2xRon** [comment] 2023-01-29 00:15
Sure thing.
[SampleDatabaseEdmx.zip](https://github.com/R4ND3LL/EntityFrameworkRuler/files/10530046/SampleDatabaseEdmx.zip)

**Comment by R4ND3LL** [comment] 2023-01-29 12:35
k. in that case, you can attach a minimal sample directly to your github comment.

**Comment by R4ND3LL** [comment] 2023-01-31 00:54
Reproduced using your sample and fixed in v1.2.17.  Thanks!

You'll want to regenerate your rules to be safe.  Scaffolding should work fine then.

**Comment by 2xRon** [comment] 2023-02-10 23:34
Awesome work!
I found two small wrinkles:

- Many-to-many joins (without a join entity) in the EDMX aren't scaffolded in the core context
- If the Referential constraint name doesn't match the FK name in the database (or the association set name) then the navigation isn't generated. (How this happened for us, I think, is we initially the referential constraint was only in the edmx and was later added to the db with a different name. This could reasonable be a wont-fix since we resolved it by fixing the edmx and the logs show up as "shares columns with an existing constraint." when this happens so it's easy to find. 

Sample:
[SampleDatabaseEdmx.zip](https://github.com/R4ND3LL/EntityFrameworkRuler/files/10711967/SampleDatabaseEdmx.zip)

1 is on the BuildingAddress table, and 2 is on the PersonAddress-Address navigation.

**Comment by R4ND3LL** [comment] 2023-02-10 23:52
Before I get into the scenario, I can tell you the second issue may be due to the IncludeUnknownColumns flag being false on the entity rule. so it's excluding the navigation because it doesn't recognize the FK.  
I'll get back to you soon

**Comment by R4ND3LL** [comment] 2023-02-14 23:34
That's a first-class sample you put together.  Makes my job easy.  thanks.

1  is fixed on build 1.2.19.
2 is not reproducible.  Nav PersonAddress-Address appears when I scaffold your sample.  Unless I'm missing something, weren't you saying the nav was missing?

**Comment by 2xRon** [comment] 2023-02-16 13:21
Fix confirmed, thank you! For two, it looks like it working when I *don't* pass a "--no-build" flag to the scaffolder.

**Comment by R4ND3LL** [comment] 2023-02-16 14:18
Can you confirm what you're seeing when you do pass "--no-build"?   PersonAddress.Address nav is missing?

**Comment by 2xRon** [comment] 2023-02-18 20:36
I'm not really sure what happened, I tried again and it's working fine now. Thanks for the help!

**Comment by R4ND3LL** [comment] 2023-02-18 21:02
When you run the scaffolding, it generates/updates the rule json file.  It sounds like may be an issue that existed on a previous run, but after the json file updated, the issue would no longer occur.  i.e. some metadata could have been misreported in the edmx.   i'll generate a new json file from the edmx and see if it happens

**Closed as completed** 2023-07-03 23:28 UTC
