### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by MisinformedDNA** [R4ND3LL/EdmxRuler#25] opened 2023-04-14 21:35 UTC
I may just be dense, but I can't figure out how to get the scaffolding to work. Should I create a working EF Core DbContext before running scaffolding? Am I scaffolding from the EDMX or from the DB? The EDMX uses its weird style for the connection string. Do I create a new connection string with a different name? Or do I replace the connection string with a normal one?

**Comment by MisinformedDNA** [comment] 2023-04-14 21:45
I might be getting closer, but am getting this error message:

```
PM> dotnet-ef dbcontext scaffold NBiEntities System.Data.SqlClient -p .\Data\XXXX\XXXX.csproj -s .\Presentation\WinForms\XXXX\XXXX.csproj
Build started...
Build succeeded.
System.IO.FileNotFoundException: Could not load file or assembly 'EntityFrameworkRuler.Design, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'EntityFrameworkRuler.Design, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureReferencedServices(IServiceCollection services, String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.CreateServiceCollection(String provider)
```

**Comment by MisinformedDNA** [comment] 2023-04-14 21:55
I finally got it to run, but I got the whole DB and nothing is named the same.

**Comment by MisinformedDNA** [comment] 2023-04-14 22:07
Ah, I generated the rules file in the same directory as the EDMX. I didn't know it was supposed to go in the startup project.

Now I have this error during scaffolding:

> DbContext rule file written to XXXX-rules.json
> Updated XXXX-rules.json in 79ms
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal(String value)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateKey(IKey key, IEntityType entityType)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateEntityType(IEntityType entityType)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateOnModelCreating(IModel model)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContext

**Comment by R4ND3LL** [comment] 2023-04-14 22:25
Looks like you've gotten past your initial questions.   scaffolding is run in the context of a blank EF Core 6 or 7 project, with a reference to EF Core packages and EFR Design package.  
Once the rule file is generated, you are not bound to the EDMX any more.   you simply run the scaffolding with the json file in the EF Core project root.  

What type of server are you using?  SQL?    It appears as though you hit an entity with a null name or related identifier.  You may be able to inspect the json for something unusual like that.  

If you install the VSIX in Visual Studio (https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler), that makes it easy to view and edit the rule file, and the save operation performs validation so if there is anything invalid about the model then that should point it out.

Outside of that, I may need a copy of your json file and DB structure to reproduce the scaffolding error.

**Comment by MisinformedDNA** [comment] 2023-04-15 02:30
The VS extension isn't showing an error when I save. I also used the extension to generate the file and it generated the same contents and still errors out. Here are some instances of null values:

```json
      "Namespace": null,
          "Navigations": [
            {
              "Name": null,
              "NewName": "Carrier",
              "FkName": "FK_t_ASN_t_Carrier",
              "ToEntity": "Carrier",
              "Multiplicity": "0..1"
            },
            {
              "Name": "Facility",
              "NewName": null,
              "FkName": "FK_t_ForcePickFacility_t_Facility",
              "ToEntity": "Facility",
              "Multiplicity": "1"
            }
```

I tried adding values in place of the null values, but still no luck. Same error every time.

**Comment by R4ND3LL** [comment] 2023-04-17 12:06
For properties and navs, its not uncommon to see nulls in the naming fields. The values are removed due to redundancy (the default name is the same as the desired output name).  

When you ran the scaffolding without the json file in the core project folder, it would have generated a json file with all the default naming content.  You could then modify a name in the json file and then rerun the scaffolding - it should apply the name change as expected.  If this works properly, then that demonstrates that there is something being done in your EDMX based rule file that is causing the error.  

I can easily identify the issue and fix it provided the json file and DB creation script.  If that is not an option for you, then I can give you pointers on how to debug the EFR source yourself, however that scenario may get complex.

**Comment by MisinformedDNA** [comment] 2023-04-17 15:13
Thank you. I'll take the pointers on how to debug.

**Comment by R4ND3LL** [comment] 2023-04-17 15:50
Debugging the exception will be the easy part.  Here goes:
1) Download the source, open EntityFrameworkRuler.sln
2) Try to compile the solution. if it complains about a missing SDK version, just delete the "version": "7.0.201", line from global.json
3) Assuming you are using SQL Server, we'll use the existing NorthwindTestDesign project to scaffold your DB.  It's located in the Test folder.  Expand the project and delete the folders: Context, Enums, Models..  Leave CodeTemplates as is.
4) replace the rules json file in this project with yours.
5) ensure you have "break on all exceptions" turned on.
6) open a dev terminal in the NorthwindTestDesign folder and execute your scaffold command.  This is what I use for Northwind, you can adjust it to use your connection string:
dotnet ef dbcontext scaffold "data source=localhost;initial catalog=Northwind;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c NorthwindEntities -f  --context-dir Context
6) the IDE may notify you about attaching the debugger to the scaffolding / design process.  proceed with that and you should then break on the exception.
7) you can inspect whats happening to determine cause.  may be helpful to send me screen shots of the local watches at the level of the exception, as well as at the top-most EFR call in the stack.  and the stack itself.

**Comment by MisinformedDNA** [comment] 2023-04-18 15:48
Interesting, it ran without any errors. I'll have to try it again in my own project. However, it's adding entities to the rules file and generating those entities that weren't there initially.

**Comment by MisinformedDNA** [comment] 2023-04-18 16:09
I have a repro if I switch all the EF Core references in your project to 6.0.0.

> System.ArgumentNullException
>   HResult=0x80004003
>   Message=Value cannot be null. (Parameter 'name')
>   Source=Microsoft.EntityFrameworkCore.Relational
>   StackTrace:
>    at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName) in /_/src/Shared/Check.cs:line 30
>    at Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Table(String name, String schema) in /_/src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs:line 63
>    at Microsoft.EntityFrameworkCore.RelationalKeyExtensions.GetName(IReadOnlyKey key) in /_/src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs:line 28
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateKey(IKey key, IEntityType entityType)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateEntityType(IEntityType entityType)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateOnModelCreating(IModel model)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.GenerateClass(IModel model, String contextName, String connectionString, Boolean suppressConnectionStringWarning, Boolean suppressOnConfiguring)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpDbContextGenerator.WriteCode(IModel model, String contextName, String connectionString, String contextNamespace, String modelNamespace, Boolean useDataAnnotations, Boolean useNullableReferenceTypes, Boolean suppressConnectionStringWarning, Boolean suppressOnConfiguring)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
>    at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
>    at EntityFrameworkRuler.Design.Services.RuledReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions) in C:\repos\EntityFrameworkRuler\src\EntityFrameworkRuler.Design\Services\RuledReverseEngineerScaffolder.cs:line 50

Down the stack, I also see that `databaseOptions.Tables` is empty.

![image](https://user-images.githubusercontent.com/1784452/232837879-c42131ba-92db-4495-9d55-c7d73ad103cc.png)

**Comment by R4ND3LL** [comment] 2023-04-18 18:35
Excellent.     

Inspecting....

**Comment by R4ND3LL** [comment] 2023-04-18 21:13
The issue is EF Core 6 reads each entity's table name annotation and throws an error if it doesn't exist.  In the case of views, they dont have a "table name", they have a "view name" instead.  I applied a hack to get around this by adding the missing table name annotation.  Reference the new version 1.2.27.

However, in your configuration file you'll now see entity.ToTable("...") as well as entity.ToView("...").  In my brief testing, it looks like this runs fine, however, if you hit runtime issues then the extra ToTable line will have to be removed. 

Note, many of the advanced EDMX features like inheritance are not supported in EFCore6.  This is because the EF Core 6 model generation code is not equipped to generate those features, as they were never anticipated when scaffolding.   EF7 on the other hand, uses t4 files to generate output, which can be tweaked to generate base class references (for inheritance scenarios) etc.    The T4s in the northwind test project fully support those features currently.  So if there is no major reason for you to stay on EF Core 6, I strongly suggest moving to 7

**Closed as completed by R4ND3LL** 2023-04-18 21:13 UTC
