### ISSUE TITLE
TPT Issues

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#8] opened 2023-01-14 01:24 UTC
Hi Mark.  I am working on the code again and I have run into a new issue.  I have the following tables in SQL:

![image](https://user-images.githubusercontent.com/119625172/212443708-cd40549b-8d14-4a50-b474-ad5416d30894.png)

DefinitionID is Identity on the BaseDefinition table and all relations are between DefinitionIDs.

In the EDMX I would set the Base Type on LatheSurfaceDefinition and BaseParasolidDefinition to BaseDefinition.  I would set ParasolidToolBodyEvolution Base Type to BaseParasolidDefinition.  I would then remove the DefinitionID field from all the tables in the EDMX except for the BaseDefinition table.

How do I do this with EFCore?  I have tried using Not Mapped on the DefinitionIDs and I tried to set the Base Type in your UI.  This does not seem to work.  After scaffolding, the classes all have a DefinitionID property as well as a BaseDefinition navigation property.

Thanks!

**Comment by R4ND3LL** [comment] 2023-01-14 13:24
See my last comment on issue R4ND3LL/EntityFrameworkRuler#3.

Most of the methods like GetProperties() are recursive, meaning they include the props of base type entities automatically.  You need to adjust your T4 to filter out the props to only that of the declaring type such as:
```csharp
EntityType.GetProperties().Where(o => o.DeclaringEntityType == EntityType)
```
Same for indexes, foreign keys, etc in the configuration:
[EntityTypeConfiguration.t4](https://github.com/R4ND3LL/EntityFrameworkRuler/blob/main/src/Tests/NorthwindTestDesign/CodeTemplates/EFCore/EntityTypeConfiguration.t4)

**Comment by jdanielpa** [comment] 2023-01-14 16:25
I am having some trouble getting the behavior I need.

1. I tried to add in the the EntityTypeConfiguration.t4 to my solution but it gets renamed to .bak when I run scaffolding:

![image](https://user-images.githubusercontent.com/119625172/212482428-d77d2fb9-f51d-4cf8-8cab-a9fd5f80e702.png)

2. I updated the EntityType.t4 to:
public partial class <#= EntityType.Name #> <# if (EntityType.BaseType?.Name!=null) { #>: <#= EntityType.BaseType.Name #><# } #>
but after scaffolding, the base types are still not set on the inheriting classes.  

3. The properties seem to only include the declaring types already so that is good.  I tried to remove the navigations using:
    
foreach (var navigation in EntityType.GetNavigations().Where(o => o.DeclaringEntityType == EntityType))

4. Once I get the configuration working, can you tell me how I would remove for example the DefinitionID property and Definition navigation for a class named BaseParasolidDefinition : BaseDefinition ?  

thanks for the help.

**Comment by R4ND3LL** [comment] 2023-01-17 15:28
1. EntityTypeConfiguration t4 will be added or removed automatically based on the setting in the json file.  "Split Entity Type Configurations" in the editor when the context object is selected.
2. Did you generate a new json file from the EDMX after the inheritance features were added, or just try to edit the json yourself to specify inheritance?  A few new pieces of info had to be extracted from the EDMX.  Generate a new json file and try with that first. 
3. If the DefinitionID property is either appearing in your entity because its a part of the base entity and you haven't filtered it out in the T4, or else its in the json table configuration as a property that you want mapped.   Same as when doing table splitting, either just mark the property  as "Not Mapped" or remove the property from the PROPERTIES tab in the editor (assuming the table has Include Unknown Columns = off)

**Comment by jdanielpa** [comment] 2023-01-17 16:57
Good catch.  I did not regenerate the json file.  
- I think I am getting closer.  I tried to generate the json file using the command line but I get an error:

> edmx path: D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Models\Context\OptiCamModel.edmx
> project base path: D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.OptiCAM.Core.Data
> 
> Error: Error generating output for EntityFrameworkRuler.Rules.DbContextRule: Object reference not set to an instance of an object.

If I use your tool it generate the json file it works.  Strange the command line fails.  I am good to use your tool but I thought you should know in case it points to another issue.

- When I run the scaffolding on the new json file, I get the attached results:
[ScaffoldingResults.txt](https://github.com/R4ND3LL/EntityFrameworkRuler/files/10437431/ScaffoldingResults.txt)

I am not sure why the JobSessionDetails1 is giving trouble.  Do you see any issue:
![image](https://user-images.githubusercontent.com/119625172/212960825-e03b2857-e6c2-4844-8b43-6f45f624456f.png)

- The scaffolding tool seems to hang most of the time now.  It will run on occasion but usually hangs at:

> dotnet ef dbcontext scaffold "data source=localhost;initial catalog=OptiCAM;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -c OptiCAMEntities -f -v --no-build
> Using project 'D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.OptiCAM.Core.Data\JJV.OptiCAM.Core.Data.csproj'.
> Using startup project 'D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.OptiCAM.Core.Data\JJV.OptiCAM.Core.Data.csproj'.
> Writing 'D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.OptiCAM.Core.Data\obj\JJV.OptiCAM.Core.Data.csproj.EntityFrameworkCore.targets'...
> dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\jdaniel\AppData\Local\Temp\tmp9821.tmp /verbosity:quiet /nologo D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.OptiCAM.Core.Data\JJV.OptiCAM.Core.Data.csproj

I am not sure what is causing the hang since nothing is reported but this is the first time I have seen any hangs at all.  Could it be something that has changed in your tools?

**Comment by R4ND3LL** [comment] 2023-01-17 17:54
Regarding the command line tool, did you update the version before you got that error?
```
dotnet tool update --global EntityFrameworkRuler
```

There is a lot going on in that EDMX.  Inheritance, table splitting, design time navigations (not based on db FKs), etc.   The issue may have to do with some combination of those features.  Are the entities JobSession and JobSessionDetail based on the same table?

If I had a copy of the full EDMX I could probably diagnose the issue.  If you want, you can email me the EDMX zipped up.

**Comment by jdanielpa** [comment] 2023-01-17 18:38
I did update the tool.

Yes - JobSession and JobSessionDetail are based on the same table.  In the edmx JobSessionDetail is a split table.  It contains one field from the JobSession table - LatheCodeOutput.

![image](https://user-images.githubusercontent.com/119625172/212983065-15971812-21d7-4d79-acd3-4ab8042f81bd.png)

I just sent you the edmx.

**Comment by R4ND3LL** [comment] 2023-01-17 19:37
FYI, unable to reproduce an error with the command line tool
```
> efruler -g C:\DEV\TEMP.EDMX\OptiCamModel.edmx C:\DEV\TEMP.Data\
 - edmx path: C:\DEV\TEMP.EDMX\OptiCamModel.edmx
 - project base path: C:\DEV\TEMP.Data\

DbContext rule file written to OptiCamEntities-rules.json
Successfully generated 1 rule file in 454ms
```

But continuing to check it over...

**Comment by jdanielpa** [comment] 2023-01-17 19:42
Hmmm.  Here is what I get:

> efruler -g "D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Models\Context\OptiCamModel.edmx" "D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.OptiCAM.Core.Data"
>  - edmx path: D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Models\Context\OptiCamModel.edmx
>  - project base path: D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.OptiCAM.Core.Data
> 
> Error: Error generating output for EntityFrameworkRuler.Rules.DbContextRule: Object reference not set to an instance of an object.

**Comment by R4ND3LL** [comment] 2023-01-19 20:24
Found the problem for rule gen.  Single ended navigations such as SessionStatus.SessionErrors.  SessionError has no inverse.  Resolved the null ref error.  You may want to generate again incase  all the nav info was not captured.

Currently, the T4s expect bidirectional navigations and will throw null ref errors if one end is empty.  So rather than requiring that T4s be modified, EFR will scaffold entities with both ends filled in.  Try it using latest version and let me know what happens.

**Comment by jdanielpa** [comment] 2023-01-19 21:48
I am trying to test now.  Ever since I upgraded dotnet ef, It hangs on me 75% of the time.  This happens on multiple projects using different databases.  When I run the scaffolding tool, this is what I see most of the time:

> dotnet ef DbContext Scaffold "data source=localhost;initial catalog=OptiCAM_6;persist security info=True;Integrated Security=SSPI;TrustServerCertificate=True;"  Microsoft.EntityFrameworkCore.SqlServer -o "D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\Models" --force --project "D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\JJV.PA.OptiCAM.Core.Data.csproj" --verbose --no-build
> Using project 'D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\JJV.PA.OptiCAM.Core.Data.csproj'.
> Using startup project 'D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\JJV.PA.OptiCAM.Core.Data.csproj'.
> Writing 'D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\obj\JJV.PA.OptiCAM.Core.Data.csproj.EntityFrameworkCore.targets'...
> dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\jdaniel\AppData\Local\Temp\tmp43C6.tmp /verbosity:quiet /nologo D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\JJV.PA.OptiCAM.Core.Data.csproj
> Writing 'D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\obj\JJV.PA.OptiCAM.Core.Data.csproj.EntityFrameworkCore.targets'...
> dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\jdaniel\AppData\Local\Temp\tmp456D.tmp /verbosity:quiet /nologo D:\JJV\Development\Workspaces\OpticalToolingEngineering\OptiCAM\Main\JJV.PA.OptiCAM.Core.Data\JJV.PA.OptiCAM.Core.Data.csproj

I have left it to sit at that point for hours but it never finishes.  Sometimes I restart VS2022 and then it works.  Sometimes I have to reboot.  Do you have any idea why this would happen or how I should go about debugging it?  I re-installed VS2022 hoping that would do it but it didn't.

Thanks

**Comment by R4ND3LL** [comment] 2023-01-19 21:53
To confirm whether EFR is playing a role here; if you remove references to the EFR Design package, does it still freeze when scaffolding?  

I'm not sure why you would experience a hang but I could possibly test the scaffolding for you if I had the DB creation script.  I debug it all the time so I can easily see what's going on.

**Comment by jdanielpa** [comment] 2023-01-19 21:55
I will test that out.  After rebooting, I was able to regenerate the rules file and execute the scaffolding.  I get an error during scaffolding.  Here is the scaffolding output:
[ScaffoldingResults.txt](https://github.com/R4ND3LL/EntityFrameworkRuler/files/10461420/ScaffoldingResults.txt)

**Comment by jdanielpa** [comment] 2023-01-19 21:59
Wait a minute.  This error might be my issue.  Standby...

**Comment by jdanielpa** [comment] 2023-01-19 22:49
So I renamed the User properties in the edmx that I thought were causing the issue but I still get the error:

> 
> RULED: Navigation LatheInfo.ToolPosts defined
> RULED: Navigation User.UserUpdatedBy defined
> RULED: Correcting navigation User.InverseUserUpdatedBy name to 'UserUpdatedBy'...
> RULED: Foreign key FK_LatheInfo_CreatedBy omitted.
> RULED: Foreign key FK_LatheInfo_UpdatedBy omitted.
> System.ArgumentException: An item with the same key has already been added. Key: EntityType: BaseParasolidLatheDefinition (Dictionary<string, object>) Base: BaseParasolidDefinition (Dictionary<string, object>) CLR Type: Dictionary<string, object>
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)

Any ideas?  I can send you the updated edmx if that would help.

Also, I removed EFR from the solution but scaffolding still hangs.  I have had to reboot 2 more times to get it to execute.

**Comment by jdanielpa** [comment] 2023-01-19 23:07
I removed a foreign key that I believe was causing that issue but now I see:

> RULED: Navigation ToolPost.LatheInfo defined
> RULED: Navigation LatheInfo.ToolPosts defined
> RULED: Foreign key FK_LatheInfo_CreatedBy omitted.
> RULED: Foreign key FK_LatheInfo_UpdatedBy omitted.
> System.ArgumentException: An item with the same key has already been added. Key: EntityType: BaseParasolidLatheDefinition (Dictionary<string, object>) Base: BaseParasolidDefinition (Dictionary<string, object>) CLR Type: Dictionary<string, object>

The LatheInfo table has 2 relations to the User table - one for CreatedBy and one for UpdatedBy.  Is this a problem for EF?

**Comment by R4ND3LL** [comment] 2023-01-19 23:10
Hard to say offhand.  The dictionary is likely internal to EF Core. I would need at least the call stack to know more.  

Best options are:
1) Generate a DB creation script and email it to me. Instructions for SSMS can be seen [here](https://www.dataaccess.com/blog/systems-environments/sharing-sql-server-databases-via-scripting-1336)
2) Load up the EFR source code, add your Data project to the EFR solution, remove the Design nuget package reference from your Data project, and instead reference the Design project directly.  Launch the scaffolding as usual in the terminal, with build option enabled, and you will get a debugger prompt to join the scaffolding process.  You can then debug it all.

No, multiple navigations in any kind of configuration should not be a problem.

**Comment by jdanielpa** [comment] 2023-01-19 23:31
Here is the script: edited
Let me know once you get it so I can remove it.

**Comment by R4ND3LL** [comment] 2023-01-19 23:39
Got it. what's your SQL Server version?

**Comment by R4ND3LL** [comment] 2023-01-19 23:45
I got it mostly loaded. it seems the Settings table is missing from the script tho.  
I have 31 tables total

**Comment by jdanielpa** [comment] 2023-01-20 00:14
That is strange.  Settings is a table that I deleted - it is no longer needed.  Where are you seeing it?
 BTW - SQL Server 2019

**Comment by R4ND3LL** [comment] 2023-01-20 00:16
Its referenced by some of the views in the script.  No big deal, I reproduced the problem.

**Comment by jdanielpa** [comment] 2023-01-24 13:29
Are you having any luck with the problem?

**Comment by R4ND3LL** [comment] 2023-01-24 13:50
Yes.  To identify what's going on in EFCore I've loaded the EF source code and setup debugging of the scaffolding process for your DB.  Part of the problem is the mixing of inheritance strategies either within the same or connected hierarchy.  It's led me back to making some enhancements to the rule generation.  I'll know soon if that resolves the problem.

Specifically, ParasolidToolBodyEvolution links to base type BaseParasolidDefinition via TPT mapping.  But BaseParasolidDefinition is already participating in a TPH mapping with other entities.

In EFCore, a hierarchy root entity can participate in 1 mapping at a time.  The root has a single annotation for inheritance strategy (TPH, TPT, TPC) so it cannot hold 2 values. 

I also noticed that some primary keys were not mapped.  This is required when using foreign keys.

Also, this is not a problem per se, but EF Core docs caution you against using TPT mapping stating: Every query involves joins. Use only as last resort they say.  It's a performance concern on large tables.

**Comment by jdanielpa** [comment] 2023-01-24 15:54
Yes - I am aware of the TPT performance issues but the tables participating in TPT are very small.  

However, I believe I can move the BaseDefinition fields to LatheSurfaceDefinition and BaseParasolidDefinition and lose that table.  Also, I believe just noticed a mistake.  I believe CutStageDefinition should have the base type set to LatheSurfaceDefinition in the edmx - not BaseDefinition.

![image](https://user-images.githubusercontent.com/119625172/214341892-c4da9b60-4d8e-4a32-8a6e-17b55d3952cc.png)


Let me know if those changes would help.  I can update my edmx and database and send you the updates.

**Comment by R4ND3LL** [comment] 2023-01-24 16:29
The two specific problems are:
1) BaseParasolidDefinition is a TPH root, and should not have a Base Type defined.  In theory, this should be supported by EF Core but currently hits a bug in its scaffolding code.  Only way to keep the base type is to open an issue against EF Core and get them to fix the bug.
2) ParasolidToolBodyEvolution links to base type BaseParasolidDefinition via TPT mapping. But BaseParasolidDefinition is already participating in a TPH mapping with other entities.  ParasolidToolBodyEvolution's Base Type is therefore invalid and must be cleared.  Because a hierarchical root can only support one inheritance strategy at a time, this will not likely be supported any time soon by EF Core. i.e. they would consider this "as designed", and adding support would require community demand.

So you can work on resolving the above modelling issues.  If you think item 1 warrants an EF Core issue to be opened, I can probably do that.

In the meantime, I'm cleaning up some EFR issues with mixed inheritance and will have a release soon.  For rule generation, I added detection for these scenarios and added warnings to the output.

**Comment by jdanielpa** [comment] 2023-01-24 20:09
OK.  I have removed the BaseDefinition table and cleaned up the BaseParasolidDefinition  inheritances.  I am now looking at ParasolidToolBodyEvolution.  Not sure the fix yet.  Ill keep you posted

**Comment by R4ND3LL** [comment] 2023-01-24 21:09
NuGet packages v1.2.5 has been published. Along with a new VSIX.  I made lot of changes with respect to your mixed inheritance scenarios.  A brief review of the scaffolded output looked good.  Let me know how that goes.

**Comment by R4ND3LL** [comment] 2023-01-26 22:20
Based on latest version v1.2.14 working fine on my copy of your context with TPH, I'm going to assume that TPT should be fine too.  Keep in mind, if there is an anomaly in the configuration that needs adjustment, you can take advantage of the "partial" class definitions to add your own implementation and customize further (without modifying the generated code directly).

This is especially customizable when using the entity configuration splitting option.  (each entity config can be easily extended in a seperate file)

Let me know if you hit another TPT issue

**Closed as completed by R4ND3LL** 2023-01-26 22:20 UTC
