### ISSUE TITLE
Navigation property missing

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#16] opened 2023-01-25 21:09 UTC
One of my classes has one navigation property that is not showing up.  LatheSurfaceDefinitions shows as expected bur JobSessions does not:

![image](https://user-images.githubusercontent.com/119625172/214690412-b3139eb8-1006-49f0-a970-52be32d61db6.png)

Any ideas?  Here is the scaffolding results:
[scaffoldResults.txt](https://github.com/R4ND3LL/EntityFrameworkRuler/files/10503687/scaffoldResults.txt)

JobSession is a table that has a field split out into JobSessionDetails.  maybe that is a clue?

**Comment by jdanielpa** [comment] 2023-01-26 00:04
I also noticed my JobSessions class is missing navigation properties:
![image](https://user-images.githubusercontent.com/119625172/214721372-4759767a-b0e3-4113-aefb-e091bc09d2fb.png)

3 of the properties made it (green arrows) - they all have Multiplicity of *
The others didn't make it (red box) have Multiplicity of 0..1

Maybe this is another clue?

**Comment by R4ND3LL** [comment] 2023-01-26 00:16
Yes it's directly related to it being a split table.  This requires a bit of a dance with EF Core to make the scaffolding happy.  I'm looking into possible solutions.

**Comment by R4ND3LL** [comment] 2023-01-26 22:14
Fixed on v1.2.14.    Your context is up and running on my copy.  This latest version prevents TPH hierarchies from linking to TPT base types.  It will print warnings if that scenario is encountered.  I confirmed that it is not supported in EF 7 officially.

You also encountered the following error but I'm not sure which issue it was attached to.  
```
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
```

This is not very obvious from the description, but the issue is actually a NULL found in the TPH Discriminator column.   Without a Discriminator value, how can EF know which derived type to create?   As a rule of thumb, your Discriminator columns, such as [ParasolidDefinitionClassName], should be non-nullable, and always filled in.

**Closed as completed by R4ND3LL** 2023-01-26 22:14 UTC

**Comment by jdanielpa** [comment] 2023-01-27 00:11
If I set ParasolidDefinitionClassName field to NOT NULL is SQL then I get an error when I refresh the EDMX:

`Error 3023: Problem in mapping fragments starting at lines 2506, 2517, 2523, 2535, 2547, 2553, 2565:Column ParasolidDefinition.ParasolidDefinitionClassName has no default value and is not nullable. A column value is required to store entity data.`

How to I resolve this?

**Comment by R4ND3LL** [comment] 2023-01-27 13:03
So you set the SQL column as non-nullable and replaced all the nulls in that column with values?

Try this: https://stackoverflow.com/questions/12684972/issue-in-ef-mapping-fragment-no-default-value-and-is-not-nullable

Ensure that the EDMX column was also updated to Nullable=false.  The EDMX doesn't always catch nullable changes when refreshing.

Note, EDMX issues are well beyond the scope of EFR.

**Comment by jdanielpa** [comment] 2023-01-27 13:30
That fixed it - The column was set to Nullable=false but it did not have a default value.
